# 履约驱动酒店管理系统 - 生产环境
version: '3.8'

services:
  # 后端API服务
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - COUCHDB_URL=http://couchdb:5984
      - CORS_ORIGIN=https://archpeng.github.io
    depends_on:
      - couchdb
      - redis
    restart: unless-stopped
    networks:
      - fulfillment-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # CouchDB数据库
  couchdb:
    image: couchdb:3.3
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-secure_password_2025}
    volumes:
      - couchdb-data:/opt/couchdb/data
      - couchdb-config:/opt/couchdb/etc/local.d
    restart: unless-stopped
    networks:
      - fulfillment-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - fulfillment-network
    command: redis-server --appendonly yes

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - fulfillment-network

volumes:
  couchdb-data:
    driver: local
  couchdb-config:
    driver: local
  redis-data:
    driver: local

networks:
  fulfillment-network:
    driver: bridge